### ISSUE TITLE
Issue in the sendMetrics function

### ISSUE THREAD

**Issue by maddop** [CA-APM/ca-apm-fieldpack-docker#3]
I'm attempting the docker fieldpack on RHEL7.1 connecting to the EPAgent version 10.3.0

Docker is configured correctly as per your guidance. I'm using Python 3.5.

I'm issuing the command: 

`python3.5 docker.py -H 127.0.0.1 -p 8080 -d localhost -r 2376 -c /etc/docker/cert.pem -k /etc/docker/key.pem -v
`

I'm seeing the following error:

`Verbose enabled
Submitting to: http://127.0.0.1:8080/apm/metricFeed
/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)

Response:
Traceback (most recent call last):
  File "docker.py", line 326, in <module>
    main(sys.argv)
  File "docker.py", line 312, in main
    sendMetrics(url, headers, metricDict, options.verbose)
  File "docker.py", line 254, in sendMetrics
    response = json.loads(r.text)
  File "/usr/local/lib/python3.5/json/**init**.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by ggrossbe** [comment]
Hi Madoop,

let me test this and get back to you later today.

Ciao,
Guenter

**Comment by maddop** [comment]
thanks Guenter.
Looking forward to your results.
cheers
Paul

**Comment by maddop** [comment]
Guenter...
Apologies, turns out to be user error!!!

I added some further debugging into the code to help identify my issue.
It turned out that I was getting a `<Response [404]>` from the request call:

`r = requests.post(url, data = json.dumps(metricDict), headers = headers)`

Further checking showed I had another process running on the same port as the introscope.epagent.config.httpServerPort

Once i corrected this, everything is working great.

cheers,
Paul

**Comment by ggrossbe** [comment]
Cool!
