### ISSUE TITLE
Invalid metric value

### ISSUE THREAD

**Issue by maddop** [CA-APM/ca-apm-fieldpack-docker#4]
Hi,
We are using the fieldpack on RHEL7.1 with Docker 1.8.2-el7 on epagent 10.1 

It appears to be producing an invalid metric value error:

```
Response:
{
    "errorCode": 1010,
    "validCount": 387,
    "invalidCount": 1,
    "errorMessage": "One or more metric specifications were invalid",
    "metricErrors": [
        {
            "metricErrorCode": 1013,
            "metricErrorMsg": "Invalid metric value",
            "metricErrorIndex": 1,
            "metricName": "Docker|<<OUR HOSTNAME>>:Total Memory"
        }
    ]
}
```

If i enable the the debug line in writeMetrics :

`print('type of {} is {}, name = {}, value = {}'.format(key, type(values[key]), name, values[key]))`

It prints out what you would expect:

`type of MemTotal is <type 'int'>, name = :Total Memory, value = 7835488256`

However, it continues to print the above error.

The metric is greyed out in the webview investigator.
Any thoughts?

**Comment by ggrossbe** [comment]
I changed the metric type to long for memory metrics. Can you give it a try now?

**Comment by maddop** [comment]
Perfect!!
Just tested and its working great now - no issues.

thanks.

**Comment by ggrossbe** [comment]
Great!
